/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalImpressumRouteImport } from './routes/legal.impressum'
import { Route as LegalDatenschutzRouteImport } from './routes/legal.datenschutz'
import { Route as LegalAgbRouteImport } from './routes/legal.agb'
import { Route as AuthenticatedShoppingListRouteImport } from './routes/_authenticated/shopping-list'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedIngredientsRouteImport } from './routes/_authenticated/ingredients'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes.index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedCookbooksIndexRouteImport } from './routes/_authenticated/cookbooks.index'
import { Route as CookbooksSharedTokenRouteImport } from './routes/cookbooks.shared.$token'
import { Route as AuthenticatedRecipesNewRouteImport } from './routes/_authenticated/recipes.new'
import { Route as AuthenticatedProfileProgressRouteImport } from './routes/_authenticated/profile.progress'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'
import { Route as AuthenticatedCookbooksNewRouteImport } from './routes/_authenticated/cookbooks.new'
import { Route as AuthenticatedBrandsIdRouteImport } from './routes/_authenticated/brands.$id'
import { Route as AuthenticatedRecipesIdIndexRouteImport } from './routes/_authenticated/recipes.$id.index'
import { Route as AuthenticatedCookbooksIdIndexRouteImport } from './routes/_authenticated/cookbooks.$id.index'
import { Route as AuthenticatedRecipesIdEditRouteImport } from './routes/_authenticated/recipes.$id.edit'
import { Route as AuthenticatedRecipesIdCookRouteImport } from './routes/_authenticated/recipes.$id.cook'
import { Route as AuthenticatedProfileStatsWeightRouteImport } from './routes/_authenticated/profile.stats.weight'
import { Route as AuthenticatedProfileStatsStreakRouteImport } from './routes/_authenticated/profile.stats.streak'
import { Route as AuthenticatedProfileStatsSeasonsRouteImport } from './routes/_authenticated/profile.stats.seasons'
import { Route as AuthenticatedProfileStatsRankRouteImport } from './routes/_authenticated/profile.stats.rank'
import { Route as AuthenticatedProfileStatsNutritionRouteImport } from './routes/_authenticated/profile.stats.nutrition'
import { Route as AuthenticatedProfileStatsBadgesRouteImport } from './routes/_authenticated/profile.stats.badges'
import { Route as AuthenticatedProfileSettingsWeightRouteImport } from './routes/_authenticated/profile.settings.weight'
import { Route as AuthenticatedProfileSettingsTrackingRouteImport } from './routes/_authenticated/profile.settings.tracking'
import { Route as AuthenticatedProfileSettingsTargetsRouteImport } from './routes/_authenticated/profile.settings.targets'
import { Route as AuthenticatedProfileSettingsSideDishesRouteImport } from './routes/_authenticated/profile.settings.side-dishes'
import { Route as AuthenticatedProfileSettingsQuickEntriesRouteImport } from './routes/_authenticated/profile.settings.quick-entries'
import { Route as AuthenticatedProfileSettingsPlanRouteImport } from './routes/_authenticated/profile.settings.plan'
import { Route as AuthenticatedProfileSettingsPatchNotesRouteImport } from './routes/_authenticated/profile.settings.patch-notes'
import { Route as AuthenticatedProfileSettingsPasswordRouteImport } from './routes/_authenticated/profile.settings.password'
import { Route as AuthenticatedProfileSettingsExportRouteImport } from './routes/_authenticated/profile.settings.export'
import { Route as AuthenticatedProfileSettingsEmailRouteImport } from './routes/_authenticated/profile.settings.email'
import { Route as AuthenticatedProfileSettingsDeleteRouteImport } from './routes/_authenticated/profile.settings.delete'
import { Route as AuthenticatedProfileSettingsBodyRouteImport } from './routes/_authenticated/profile.settings.body'
import { Route as AuthenticatedProfileSettingsAvatarRouteImport } from './routes/_authenticated/profile.settings.avatar'
import { Route as AuthenticatedProfileSettingsAppearanceRouteImport } from './routes/_authenticated/profile.settings.appearance'
import { Route as AuthenticatedCookbooksIdEditRouteImport } from './routes/_authenticated/cookbooks.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/legal/impressum',
  path: '/legal/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDatenschutzRoute = LegalDatenschutzRouteImport.update({
  id: '/legal/datenschutz',
  path: '/legal/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAgbRoute = LegalAgbRouteImport.update({
  id: '/legal/agb',
  path: '/legal/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShoppingListRoute =
  AuthenticatedShoppingListRouteImport.update({
    id: '/shopping-list',
    path: '/shopping-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIngredientsRoute =
  AuthenticatedIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCookbooksIndexRoute =
  AuthenticatedCookbooksIndexRouteImport.update({
    id: '/cookbooks/',
    path: '/cookbooks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CookbooksSharedTokenRoute = CookbooksSharedTokenRouteImport.update({
  id: '/cookbooks/shared/$token',
  path: '/cookbooks/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecipesNewRoute = AuthenticatedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileProgressRoute =
  AuthenticatedProfileProgressRouteImport.update({
    id: '/profile/progress',
    path: '/profile/progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCookbooksNewRoute =
  AuthenticatedCookbooksNewRouteImport.update({
    id: '/cookbooks/new',
    path: '/cookbooks/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsIdRoute = AuthenticatedBrandsIdRouteImport.update({
  id: '/brands/$id',
  path: '/brands/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipesIdIndexRoute =
  AuthenticatedRecipesIdIndexRouteImport.update({
    id: '/recipes/$id/',
    path: '/recipes/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCookbooksIdIndexRoute =
  AuthenticatedCookbooksIdIndexRouteImport.update({
    id: '/cookbooks/$id/',
    path: '/cookbooks/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesIdEditRoute =
  AuthenticatedRecipesIdEditRouteImport.update({
    id: '/recipes/$id/edit',
    path: '/recipes/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesIdCookRoute =
  AuthenticatedRecipesIdCookRouteImport.update({
    id: '/recipes/$id/cook',
    path: '/recipes/$id/cook',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileStatsWeightRoute =
  AuthenticatedProfileStatsWeightRouteImport.update({
    id: '/profile/stats/weight',
    path: '/profile/stats/weight',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileStatsStreakRoute =
  AuthenticatedProfileStatsStreakRouteImport.update({
    id: '/profile/stats/streak',
    path: '/profile/stats/streak',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileStatsSeasonsRoute =
  AuthenticatedProfileStatsSeasonsRouteImport.update({
    id: '/profile/stats/seasons',
    path: '/profile/stats/seasons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileStatsRankRoute =
  AuthenticatedProfileStatsRankRouteImport.update({
    id: '/profile/stats/rank',
    path: '/profile/stats/rank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileStatsNutritionRoute =
  AuthenticatedProfileStatsNutritionRouteImport.update({
    id: '/profile/stats/nutrition',
    path: '/profile/stats/nutrition',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileStatsBadgesRoute =
  AuthenticatedProfileStatsBadgesRouteImport.update({
    id: '/profile/stats/badges',
    path: '/profile/stats/badges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsWeightRoute =
  AuthenticatedProfileSettingsWeightRouteImport.update({
    id: '/profile/settings/weight',
    path: '/profile/settings/weight',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsTrackingRoute =
  AuthenticatedProfileSettingsTrackingRouteImport.update({
    id: '/profile/settings/tracking',
    path: '/profile/settings/tracking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsTargetsRoute =
  AuthenticatedProfileSettingsTargetsRouteImport.update({
    id: '/profile/settings/targets',
    path: '/profile/settings/targets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsSideDishesRoute =
  AuthenticatedProfileSettingsSideDishesRouteImport.update({
    id: '/profile/settings/side-dishes',
    path: '/profile/settings/side-dishes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsQuickEntriesRoute =
  AuthenticatedProfileSettingsQuickEntriesRouteImport.update({
    id: '/profile/settings/quick-entries',
    path: '/profile/settings/quick-entries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsPlanRoute =
  AuthenticatedProfileSettingsPlanRouteImport.update({
    id: '/profile/settings/plan',
    path: '/profile/settings/plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsPatchNotesRoute =
  AuthenticatedProfileSettingsPatchNotesRouteImport.update({
    id: '/profile/settings/patch-notes',
    path: '/profile/settings/patch-notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsPasswordRoute =
  AuthenticatedProfileSettingsPasswordRouteImport.update({
    id: '/profile/settings/password',
    path: '/profile/settings/password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsExportRoute =
  AuthenticatedProfileSettingsExportRouteImport.update({
    id: '/profile/settings/export',
    path: '/profile/settings/export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsEmailRoute =
  AuthenticatedProfileSettingsEmailRouteImport.update({
    id: '/profile/settings/email',
    path: '/profile/settings/email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsDeleteRoute =
  AuthenticatedProfileSettingsDeleteRouteImport.update({
    id: '/profile/settings/delete',
    path: '/profile/settings/delete',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsBodyRoute =
  AuthenticatedProfileSettingsBodyRouteImport.update({
    id: '/profile/settings/body',
    path: '/profile/settings/body',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsAvatarRoute =
  AuthenticatedProfileSettingsAvatarRouteImport.update({
    id: '/profile/settings/avatar',
    path: '/profile/settings/avatar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsAppearanceRoute =
  AuthenticatedProfileSettingsAppearanceRouteImport.update({
    id: '/profile/settings/appearance',
    path: '/profile/settings/appearance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCookbooksIdEditRoute =
  AuthenticatedCookbooksIdEditRouteImport.update({
    id: '/cookbooks/$id/edit',
    path: '/cookbooks/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ingredients': typeof AuthenticatedIngredientsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/shopping-list': typeof AuthenticatedShoppingListRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/datenschutz': typeof LegalDatenschutzRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/brands/$id': typeof AuthenticatedBrandsIdRoute
  '/cookbooks/new': typeof AuthenticatedCookbooksNewRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/profile/progress': typeof AuthenticatedProfileProgressRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/cookbooks/shared/$token': typeof CookbooksSharedTokenRoute
  '/cookbooks/': typeof AuthenticatedCookbooksIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/cookbooks/$id/edit': typeof AuthenticatedCookbooksIdEditRoute
  '/profile/settings/appearance': typeof AuthenticatedProfileSettingsAppearanceRoute
  '/profile/settings/avatar': typeof AuthenticatedProfileSettingsAvatarRoute
  '/profile/settings/body': typeof AuthenticatedProfileSettingsBodyRoute
  '/profile/settings/delete': typeof AuthenticatedProfileSettingsDeleteRoute
  '/profile/settings/email': typeof AuthenticatedProfileSettingsEmailRoute
  '/profile/settings/export': typeof AuthenticatedProfileSettingsExportRoute
  '/profile/settings/password': typeof AuthenticatedProfileSettingsPasswordRoute
  '/profile/settings/patch-notes': typeof AuthenticatedProfileSettingsPatchNotesRoute
  '/profile/settings/plan': typeof AuthenticatedProfileSettingsPlanRoute
  '/profile/settings/quick-entries': typeof AuthenticatedProfileSettingsQuickEntriesRoute
  '/profile/settings/side-dishes': typeof AuthenticatedProfileSettingsSideDishesRoute
  '/profile/settings/targets': typeof AuthenticatedProfileSettingsTargetsRoute
  '/profile/settings/tracking': typeof AuthenticatedProfileSettingsTrackingRoute
  '/profile/settings/weight': typeof AuthenticatedProfileSettingsWeightRoute
  '/profile/stats/badges': typeof AuthenticatedProfileStatsBadgesRoute
  '/profile/stats/nutrition': typeof AuthenticatedProfileStatsNutritionRoute
  '/profile/stats/rank': typeof AuthenticatedProfileStatsRankRoute
  '/profile/stats/seasons': typeof AuthenticatedProfileStatsSeasonsRoute
  '/profile/stats/streak': typeof AuthenticatedProfileStatsStreakRoute
  '/profile/stats/weight': typeof AuthenticatedProfileStatsWeightRoute
  '/recipes/$id/cook': typeof AuthenticatedRecipesIdCookRoute
  '/recipes/$id/edit': typeof AuthenticatedRecipesIdEditRoute
  '/cookbooks/$id/': typeof AuthenticatedCookbooksIdIndexRoute
  '/recipes/$id/': typeof AuthenticatedRecipesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ingredients': typeof AuthenticatedIngredientsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/shopping-list': typeof AuthenticatedShoppingListRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/datenschutz': typeof LegalDatenschutzRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/brands/$id': typeof AuthenticatedBrandsIdRoute
  '/cookbooks/new': typeof AuthenticatedCookbooksNewRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/profile/progress': typeof AuthenticatedProfileProgressRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/cookbooks/shared/$token': typeof CookbooksSharedTokenRoute
  '/cookbooks': typeof AuthenticatedCookbooksIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/cookbooks/$id/edit': typeof AuthenticatedCookbooksIdEditRoute
  '/profile/settings/appearance': typeof AuthenticatedProfileSettingsAppearanceRoute
  '/profile/settings/avatar': typeof AuthenticatedProfileSettingsAvatarRoute
  '/profile/settings/body': typeof AuthenticatedProfileSettingsBodyRoute
  '/profile/settings/delete': typeof AuthenticatedProfileSettingsDeleteRoute
  '/profile/settings/email': typeof AuthenticatedProfileSettingsEmailRoute
  '/profile/settings/export': typeof AuthenticatedProfileSettingsExportRoute
  '/profile/settings/password': typeof AuthenticatedProfileSettingsPasswordRoute
  '/profile/settings/patch-notes': typeof AuthenticatedProfileSettingsPatchNotesRoute
  '/profile/settings/plan': typeof AuthenticatedProfileSettingsPlanRoute
  '/profile/settings/quick-entries': typeof AuthenticatedProfileSettingsQuickEntriesRoute
  '/profile/settings/side-dishes': typeof AuthenticatedProfileSettingsSideDishesRoute
  '/profile/settings/targets': typeof AuthenticatedProfileSettingsTargetsRoute
  '/profile/settings/tracking': typeof AuthenticatedProfileSettingsTrackingRoute
  '/profile/settings/weight': typeof AuthenticatedProfileSettingsWeightRoute
  '/profile/stats/badges': typeof AuthenticatedProfileStatsBadgesRoute
  '/profile/stats/nutrition': typeof AuthenticatedProfileStatsNutritionRoute
  '/profile/stats/rank': typeof AuthenticatedProfileStatsRankRoute
  '/profile/stats/seasons': typeof AuthenticatedProfileStatsSeasonsRoute
  '/profile/stats/streak': typeof AuthenticatedProfileStatsStreakRoute
  '/profile/stats/weight': typeof AuthenticatedProfileStatsWeightRoute
  '/recipes/$id/cook': typeof AuthenticatedRecipesIdCookRoute
  '/recipes/$id/edit': typeof AuthenticatedRecipesIdEditRoute
  '/cookbooks/$id': typeof AuthenticatedCookbooksIdIndexRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ingredients': typeof AuthenticatedIngredientsRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/shopping-list': typeof AuthenticatedShoppingListRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/datenschutz': typeof LegalDatenschutzRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/_authenticated/brands/$id': typeof AuthenticatedBrandsIdRoute
  '/_authenticated/cookbooks/new': typeof AuthenticatedCookbooksNewRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/_authenticated/profile/progress': typeof AuthenticatedProfileProgressRoute
  '/_authenticated/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/cookbooks/shared/$token': typeof CookbooksSharedTokenRoute
  '/_authenticated/cookbooks/': typeof AuthenticatedCookbooksIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/cookbooks/$id/edit': typeof AuthenticatedCookbooksIdEditRoute
  '/_authenticated/profile/settings/appearance': typeof AuthenticatedProfileSettingsAppearanceRoute
  '/_authenticated/profile/settings/avatar': typeof AuthenticatedProfileSettingsAvatarRoute
  '/_authenticated/profile/settings/body': typeof AuthenticatedProfileSettingsBodyRoute
  '/_authenticated/profile/settings/delete': typeof AuthenticatedProfileSettingsDeleteRoute
  '/_authenticated/profile/settings/email': typeof AuthenticatedProfileSettingsEmailRoute
  '/_authenticated/profile/settings/export': typeof AuthenticatedProfileSettingsExportRoute
  '/_authenticated/profile/settings/password': typeof AuthenticatedProfileSettingsPasswordRoute
  '/_authenticated/profile/settings/patch-notes': typeof AuthenticatedProfileSettingsPatchNotesRoute
  '/_authenticated/profile/settings/plan': typeof AuthenticatedProfileSettingsPlanRoute
  '/_authenticated/profile/settings/quick-entries': typeof AuthenticatedProfileSettingsQuickEntriesRoute
  '/_authenticated/profile/settings/side-dishes': typeof AuthenticatedProfileSettingsSideDishesRoute
  '/_authenticated/profile/settings/targets': typeof AuthenticatedProfileSettingsTargetsRoute
  '/_authenticated/profile/settings/tracking': typeof AuthenticatedProfileSettingsTrackingRoute
  '/_authenticated/profile/settings/weight': typeof AuthenticatedProfileSettingsWeightRoute
  '/_authenticated/profile/stats/badges': typeof AuthenticatedProfileStatsBadgesRoute
  '/_authenticated/profile/stats/nutrition': typeof AuthenticatedProfileStatsNutritionRoute
  '/_authenticated/profile/stats/rank': typeof AuthenticatedProfileStatsRankRoute
  '/_authenticated/profile/stats/seasons': typeof AuthenticatedProfileStatsSeasonsRoute
  '/_authenticated/profile/stats/streak': typeof AuthenticatedProfileStatsStreakRoute
  '/_authenticated/profile/stats/weight': typeof AuthenticatedProfileStatsWeightRoute
  '/_authenticated/recipes/$id/cook': typeof AuthenticatedRecipesIdCookRoute
  '/_authenticated/recipes/$id/edit': typeof AuthenticatedRecipesIdEditRoute
  '/_authenticated/cookbooks/$id/': typeof AuthenticatedCookbooksIdIndexRoute
  '/_authenticated/recipes/$id/': typeof AuthenticatedRecipesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ingredients'
    | '/planner'
    | '/shopping-list'
    | '/legal/agb'
    | '/legal/datenschutz'
    | '/legal/impressum'
    | '/brands/$id'
    | '/cookbooks/new'
    | '/profile/$username'
    | '/profile/progress'
    | '/recipes/new'
    | '/cookbooks/shared/$token'
    | '/cookbooks/'
    | '/profile/'
    | '/recipes/'
    | '/cookbooks/$id/edit'
    | '/profile/settings/appearance'
    | '/profile/settings/avatar'
    | '/profile/settings/body'
    | '/profile/settings/delete'
    | '/profile/settings/email'
    | '/profile/settings/export'
    | '/profile/settings/password'
    | '/profile/settings/patch-notes'
    | '/profile/settings/plan'
    | '/profile/settings/quick-entries'
    | '/profile/settings/side-dishes'
    | '/profile/settings/targets'
    | '/profile/settings/tracking'
    | '/profile/settings/weight'
    | '/profile/stats/badges'
    | '/profile/stats/nutrition'
    | '/profile/stats/rank'
    | '/profile/stats/seasons'
    | '/profile/stats/streak'
    | '/profile/stats/weight'
    | '/recipes/$id/cook'
    | '/recipes/$id/edit'
    | '/cookbooks/$id/'
    | '/recipes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ingredients'
    | '/planner'
    | '/shopping-list'
    | '/legal/agb'
    | '/legal/datenschutz'
    | '/legal/impressum'
    | '/brands/$id'
    | '/cookbooks/new'
    | '/profile/$username'
    | '/profile/progress'
    | '/recipes/new'
    | '/cookbooks/shared/$token'
    | '/cookbooks'
    | '/profile'
    | '/recipes'
    | '/cookbooks/$id/edit'
    | '/profile/settings/appearance'
    | '/profile/settings/avatar'
    | '/profile/settings/body'
    | '/profile/settings/delete'
    | '/profile/settings/email'
    | '/profile/settings/export'
    | '/profile/settings/password'
    | '/profile/settings/patch-notes'
    | '/profile/settings/plan'
    | '/profile/settings/quick-entries'
    | '/profile/settings/side-dishes'
    | '/profile/settings/targets'
    | '/profile/settings/tracking'
    | '/profile/settings/weight'
    | '/profile/stats/badges'
    | '/profile/stats/nutrition'
    | '/profile/stats/rank'
    | '/profile/stats/seasons'
    | '/profile/stats/streak'
    | '/profile/stats/weight'
    | '/recipes/$id/cook'
    | '/recipes/$id/edit'
    | '/cookbooks/$id'
    | '/recipes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ingredients'
    | '/_authenticated/planner'
    | '/_authenticated/shopping-list'
    | '/legal/agb'
    | '/legal/datenschutz'
    | '/legal/impressum'
    | '/_authenticated/brands/$id'
    | '/_authenticated/cookbooks/new'
    | '/_authenticated/profile/$username'
    | '/_authenticated/profile/progress'
    | '/_authenticated/recipes/new'
    | '/cookbooks/shared/$token'
    | '/_authenticated/cookbooks/'
    | '/_authenticated/profile/'
    | '/_authenticated/recipes/'
    | '/_authenticated/cookbooks/$id/edit'
    | '/_authenticated/profile/settings/appearance'
    | '/_authenticated/profile/settings/avatar'
    | '/_authenticated/profile/settings/body'
    | '/_authenticated/profile/settings/delete'
    | '/_authenticated/profile/settings/email'
    | '/_authenticated/profile/settings/export'
    | '/_authenticated/profile/settings/password'
    | '/_authenticated/profile/settings/patch-notes'
    | '/_authenticated/profile/settings/plan'
    | '/_authenticated/profile/settings/quick-entries'
    | '/_authenticated/profile/settings/side-dishes'
    | '/_authenticated/profile/settings/targets'
    | '/_authenticated/profile/settings/tracking'
    | '/_authenticated/profile/settings/weight'
    | '/_authenticated/profile/stats/badges'
    | '/_authenticated/profile/stats/nutrition'
    | '/_authenticated/profile/stats/rank'
    | '/_authenticated/profile/stats/seasons'
    | '/_authenticated/profile/stats/streak'
    | '/_authenticated/profile/stats/weight'
    | '/_authenticated/recipes/$id/cook'
    | '/_authenticated/recipes/$id/edit'
    | '/_authenticated/cookbooks/$id/'
    | '/_authenticated/recipes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LegalAgbRoute: typeof LegalAgbRoute
  LegalDatenschutzRoute: typeof LegalDatenschutzRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  CookbooksSharedTokenRoute: typeof CookbooksSharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/legal/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/datenschutz': {
      id: '/legal/datenschutz'
      path: '/legal/datenschutz'
      fullPath: '/legal/datenschutz'
      preLoaderRoute: typeof LegalDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/agb': {
      id: '/legal/agb'
      path: '/legal/agb'
      fullPath: '/legal/agb'
      preLoaderRoute: typeof LegalAgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shopping-list': {
      id: '/_authenticated/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof AuthenticatedShoppingListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingredients': {
      id: '/_authenticated/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AuthenticatedIngredientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cookbooks/': {
      id: '/_authenticated/cookbooks/'
      path: '/cookbooks'
      fullPath: '/cookbooks/'
      preLoaderRoute: typeof AuthenticatedCookbooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cookbooks/shared/$token': {
      id: '/cookbooks/shared/$token'
      path: '/cookbooks/shared/$token'
      fullPath: '/cookbooks/shared/$token'
      preLoaderRoute: typeof CookbooksSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recipes/new': {
      id: '/_authenticated/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/progress': {
      id: '/_authenticated/profile/progress'
      path: '/profile/progress'
      fullPath: '/profile/progress'
      preLoaderRoute: typeof AuthenticatedProfileProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cookbooks/new': {
      id: '/_authenticated/cookbooks/new'
      path: '/cookbooks/new'
      fullPath: '/cookbooks/new'
      preLoaderRoute: typeof AuthenticatedCookbooksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/$id': {
      id: '/_authenticated/brands/$id'
      path: '/brands/$id'
      fullPath: '/brands/$id'
      preLoaderRoute: typeof AuthenticatedBrandsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/$id/': {
      id: '/_authenticated/recipes/$id/'
      path: '/recipes/$id'
      fullPath: '/recipes/$id/'
      preLoaderRoute: typeof AuthenticatedRecipesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cookbooks/$id/': {
      id: '/_authenticated/cookbooks/$id/'
      path: '/cookbooks/$id'
      fullPath: '/cookbooks/$id/'
      preLoaderRoute: typeof AuthenticatedCookbooksIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/$id/edit': {
      id: '/_authenticated/recipes/$id/edit'
      path: '/recipes/$id/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof AuthenticatedRecipesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/$id/cook': {
      id: '/_authenticated/recipes/$id/cook'
      path: '/recipes/$id/cook'
      fullPath: '/recipes/$id/cook'
      preLoaderRoute: typeof AuthenticatedRecipesIdCookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/stats/weight': {
      id: '/_authenticated/profile/stats/weight'
      path: '/profile/stats/weight'
      fullPath: '/profile/stats/weight'
      preLoaderRoute: typeof AuthenticatedProfileStatsWeightRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/stats/streak': {
      id: '/_authenticated/profile/stats/streak'
      path: '/profile/stats/streak'
      fullPath: '/profile/stats/streak'
      preLoaderRoute: typeof AuthenticatedProfileStatsStreakRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/stats/seasons': {
      id: '/_authenticated/profile/stats/seasons'
      path: '/profile/stats/seasons'
      fullPath: '/profile/stats/seasons'
      preLoaderRoute: typeof AuthenticatedProfileStatsSeasonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/stats/rank': {
      id: '/_authenticated/profile/stats/rank'
      path: '/profile/stats/rank'
      fullPath: '/profile/stats/rank'
      preLoaderRoute: typeof AuthenticatedProfileStatsRankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/stats/nutrition': {
      id: '/_authenticated/profile/stats/nutrition'
      path: '/profile/stats/nutrition'
      fullPath: '/profile/stats/nutrition'
      preLoaderRoute: typeof AuthenticatedProfileStatsNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/stats/badges': {
      id: '/_authenticated/profile/stats/badges'
      path: '/profile/stats/badges'
      fullPath: '/profile/stats/badges'
      preLoaderRoute: typeof AuthenticatedProfileStatsBadgesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/weight': {
      id: '/_authenticated/profile/settings/weight'
      path: '/profile/settings/weight'
      fullPath: '/profile/settings/weight'
      preLoaderRoute: typeof AuthenticatedProfileSettingsWeightRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/tracking': {
      id: '/_authenticated/profile/settings/tracking'
      path: '/profile/settings/tracking'
      fullPath: '/profile/settings/tracking'
      preLoaderRoute: typeof AuthenticatedProfileSettingsTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/targets': {
      id: '/_authenticated/profile/settings/targets'
      path: '/profile/settings/targets'
      fullPath: '/profile/settings/targets'
      preLoaderRoute: typeof AuthenticatedProfileSettingsTargetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/side-dishes': {
      id: '/_authenticated/profile/settings/side-dishes'
      path: '/profile/settings/side-dishes'
      fullPath: '/profile/settings/side-dishes'
      preLoaderRoute: typeof AuthenticatedProfileSettingsSideDishesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/quick-entries': {
      id: '/_authenticated/profile/settings/quick-entries'
      path: '/profile/settings/quick-entries'
      fullPath: '/profile/settings/quick-entries'
      preLoaderRoute: typeof AuthenticatedProfileSettingsQuickEntriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/plan': {
      id: '/_authenticated/profile/settings/plan'
      path: '/profile/settings/plan'
      fullPath: '/profile/settings/plan'
      preLoaderRoute: typeof AuthenticatedProfileSettingsPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/patch-notes': {
      id: '/_authenticated/profile/settings/patch-notes'
      path: '/profile/settings/patch-notes'
      fullPath: '/profile/settings/patch-notes'
      preLoaderRoute: typeof AuthenticatedProfileSettingsPatchNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/password': {
      id: '/_authenticated/profile/settings/password'
      path: '/profile/settings/password'
      fullPath: '/profile/settings/password'
      preLoaderRoute: typeof AuthenticatedProfileSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/export': {
      id: '/_authenticated/profile/settings/export'
      path: '/profile/settings/export'
      fullPath: '/profile/settings/export'
      preLoaderRoute: typeof AuthenticatedProfileSettingsExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/email': {
      id: '/_authenticated/profile/settings/email'
      path: '/profile/settings/email'
      fullPath: '/profile/settings/email'
      preLoaderRoute: typeof AuthenticatedProfileSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/delete': {
      id: '/_authenticated/profile/settings/delete'
      path: '/profile/settings/delete'
      fullPath: '/profile/settings/delete'
      preLoaderRoute: typeof AuthenticatedProfileSettingsDeleteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/body': {
      id: '/_authenticated/profile/settings/body'
      path: '/profile/settings/body'
      fullPath: '/profile/settings/body'
      preLoaderRoute: typeof AuthenticatedProfileSettingsBodyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/avatar': {
      id: '/_authenticated/profile/settings/avatar'
      path: '/profile/settings/avatar'
      fullPath: '/profile/settings/avatar'
      preLoaderRoute: typeof AuthenticatedProfileSettingsAvatarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/appearance': {
      id: '/_authenticated/profile/settings/appearance'
      path: '/profile/settings/appearance'
      fullPath: '/profile/settings/appearance'
      preLoaderRoute: typeof AuthenticatedProfileSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cookbooks/$id/edit': {
      id: '/_authenticated/cookbooks/$id/edit'
      path: '/cookbooks/$id/edit'
      fullPath: '/cookbooks/$id/edit'
      preLoaderRoute: typeof AuthenticatedCookbooksIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIngredientsRoute: typeof AuthenticatedIngredientsRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedShoppingListRoute: typeof AuthenticatedShoppingListRoute
  AuthenticatedBrandsIdRoute: typeof AuthenticatedBrandsIdRoute
  AuthenticatedCookbooksNewRoute: typeof AuthenticatedCookbooksNewRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
  AuthenticatedProfileProgressRoute: typeof AuthenticatedProfileProgressRoute
  AuthenticatedRecipesNewRoute: typeof AuthenticatedRecipesNewRoute
  AuthenticatedCookbooksIndexRoute: typeof AuthenticatedCookbooksIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedCookbooksIdEditRoute: typeof AuthenticatedCookbooksIdEditRoute
  AuthenticatedProfileSettingsAppearanceRoute: typeof AuthenticatedProfileSettingsAppearanceRoute
  AuthenticatedProfileSettingsAvatarRoute: typeof AuthenticatedProfileSettingsAvatarRoute
  AuthenticatedProfileSettingsBodyRoute: typeof AuthenticatedProfileSettingsBodyRoute
  AuthenticatedProfileSettingsDeleteRoute: typeof AuthenticatedProfileSettingsDeleteRoute
  AuthenticatedProfileSettingsEmailRoute: typeof AuthenticatedProfileSettingsEmailRoute
  AuthenticatedProfileSettingsExportRoute: typeof AuthenticatedProfileSettingsExportRoute
  AuthenticatedProfileSettingsPasswordRoute: typeof AuthenticatedProfileSettingsPasswordRoute
  AuthenticatedProfileSettingsPatchNotesRoute: typeof AuthenticatedProfileSettingsPatchNotesRoute
  AuthenticatedProfileSettingsPlanRoute: typeof AuthenticatedProfileSettingsPlanRoute
  AuthenticatedProfileSettingsQuickEntriesRoute: typeof AuthenticatedProfileSettingsQuickEntriesRoute
  AuthenticatedProfileSettingsSideDishesRoute: typeof AuthenticatedProfileSettingsSideDishesRoute
  AuthenticatedProfileSettingsTargetsRoute: typeof AuthenticatedProfileSettingsTargetsRoute
  AuthenticatedProfileSettingsTrackingRoute: typeof AuthenticatedProfileSettingsTrackingRoute
  AuthenticatedProfileSettingsWeightRoute: typeof AuthenticatedProfileSettingsWeightRoute
  AuthenticatedProfileStatsBadgesRoute: typeof AuthenticatedProfileStatsBadgesRoute
  AuthenticatedProfileStatsNutritionRoute: typeof AuthenticatedProfileStatsNutritionRoute
  AuthenticatedProfileStatsRankRoute: typeof AuthenticatedProfileStatsRankRoute
  AuthenticatedProfileStatsSeasonsRoute: typeof AuthenticatedProfileStatsSeasonsRoute
  AuthenticatedProfileStatsStreakRoute: typeof AuthenticatedProfileStatsStreakRoute
  AuthenticatedProfileStatsWeightRoute: typeof AuthenticatedProfileStatsWeightRoute
  AuthenticatedRecipesIdCookRoute: typeof AuthenticatedRecipesIdCookRoute
  AuthenticatedRecipesIdEditRoute: typeof AuthenticatedRecipesIdEditRoute
  AuthenticatedCookbooksIdIndexRoute: typeof AuthenticatedCookbooksIdIndexRoute
  AuthenticatedRecipesIdIndexRoute: typeof AuthenticatedRecipesIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIngredientsRoute: AuthenticatedIngredientsRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedShoppingListRoute: AuthenticatedShoppingListRoute,
  AuthenticatedBrandsIdRoute: AuthenticatedBrandsIdRoute,
  AuthenticatedCookbooksNewRoute: AuthenticatedCookbooksNewRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
  AuthenticatedProfileProgressRoute: AuthenticatedProfileProgressRoute,
  AuthenticatedRecipesNewRoute: AuthenticatedRecipesNewRoute,
  AuthenticatedCookbooksIndexRoute: AuthenticatedCookbooksIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedCookbooksIdEditRoute: AuthenticatedCookbooksIdEditRoute,
  AuthenticatedProfileSettingsAppearanceRoute:
    AuthenticatedProfileSettingsAppearanceRoute,
  AuthenticatedProfileSettingsAvatarRoute:
    AuthenticatedProfileSettingsAvatarRoute,
  AuthenticatedProfileSettingsBodyRoute: AuthenticatedProfileSettingsBodyRoute,
  AuthenticatedProfileSettingsDeleteRoute:
    AuthenticatedProfileSettingsDeleteRoute,
  AuthenticatedProfileSettingsEmailRoute:
    AuthenticatedProfileSettingsEmailRoute,
  AuthenticatedProfileSettingsExportRoute:
    AuthenticatedProfileSettingsExportRoute,
  AuthenticatedProfileSettingsPasswordRoute:
    AuthenticatedProfileSettingsPasswordRoute,
  AuthenticatedProfileSettingsPatchNotesRoute:
    AuthenticatedProfileSettingsPatchNotesRoute,
  AuthenticatedProfileSettingsPlanRoute: AuthenticatedProfileSettingsPlanRoute,
  AuthenticatedProfileSettingsQuickEntriesRoute:
    AuthenticatedProfileSettingsQuickEntriesRoute,
  AuthenticatedProfileSettingsSideDishesRoute:
    AuthenticatedProfileSettingsSideDishesRoute,
  AuthenticatedProfileSettingsTargetsRoute:
    AuthenticatedProfileSettingsTargetsRoute,
  AuthenticatedProfileSettingsTrackingRoute:
    AuthenticatedProfileSettingsTrackingRoute,
  AuthenticatedProfileSettingsWeightRoute:
    AuthenticatedProfileSettingsWeightRoute,
  AuthenticatedProfileStatsBadgesRoute: AuthenticatedProfileStatsBadgesRoute,
  AuthenticatedProfileStatsNutritionRoute:
    AuthenticatedProfileStatsNutritionRoute,
  AuthenticatedProfileStatsRankRoute: AuthenticatedProfileStatsRankRoute,
  AuthenticatedProfileStatsSeasonsRoute: AuthenticatedProfileStatsSeasonsRoute,
  AuthenticatedProfileStatsStreakRoute: AuthenticatedProfileStatsStreakRoute,
  AuthenticatedProfileStatsWeightRoute: AuthenticatedProfileStatsWeightRoute,
  AuthenticatedRecipesIdCookRoute: AuthenticatedRecipesIdCookRoute,
  AuthenticatedRecipesIdEditRoute: AuthenticatedRecipesIdEditRoute,
  AuthenticatedCookbooksIdIndexRoute: AuthenticatedCookbooksIdIndexRoute,
  AuthenticatedRecipesIdIndexRoute: AuthenticatedRecipesIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LegalAgbRoute: LegalAgbRoute,
  LegalDatenschutzRoute: LegalDatenschutzRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  CookbooksSharedTokenRoute: CookbooksSharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
